### PR TITLE
Explicitly set .message on DocRaptorRequestException

### PR DESCRIPTION
**Pull request by jarekwg**
Resolves https://github.com/jkeyes/python-docraptor/issues/9

### CODE REVIEW

**Comment by Frozenball** [comment]
I also stumbled upon on this.

**Comment by jkeyes** [comment]
@jarekwg @Frozenball I completely forgot about this. I'll get this fixed and released to PyPi later today. The build is failing as the `--use-mirrors` argument is being used in `.travis.yml`.

**Comment by Frozenball** [comment]
Awesome!

**Comment by jkeyes** [comment]
This PR has been superseded by https://github.com/jkeyes/python-docraptor/pull/11

**Comment by jkeyes** [comment]
@jarekwg @Frozenball new release `1.2.3` on PyPI. Python 2.6 support has been removed as the version of `requests` doesn't support it anymore.

**Pull request closed without merging**
